#!/usr/bin/env python3
"""
hz_polyfit.py  —  Parametric habitable-zone boundary coefficients from ExoColumn.

Kopparapu et al. (2013, 2014) distilled their HZ calculations into a compact,
reusable parametrisation: the effective stellar flux at each HZ boundary as a
quartic in stellar effective temperature,

    S_eff(T_eff) = S_eff_sun + a*T* + b*T*^2 + c*T*^3 + d*T*^4 ,   T* = T_eff - 5780 K,

with the corresponding orbital distance recovered from

    d = sqrt( (L/L_sun) / S_eff )  AU.

This script fits that exact form to the ExoColumn HZ limits computed in
hz_figure7.py (cached in hz_figure7.npz) for the three radiatively-determined
boundaries the model resolves:

    runaway greenhouse  (inner, S_eff at T_c = 647 K runaway onset)
    moist greenhouse    (inner, stratospheric H2O VMR reaches 3e-3)
    maximum greenhouse  (outer, S_eff minimum of the dense-CO2 sweep)

The empirical "recent Venus" and "early Mars" limits of Kopparapu et al. are
solar-system-evidence boundaries, not radiative-transfer results, so they are
outside ExoColumn's scope and are not fit here.

Outputs (written next to this script) — the reusable deliverable, a drop-in
replacement for Kopparapu's Table 3 with the ExoColumn radiation core:
  * hz_coefficients.txt  — human/machine-readable coefficient table.
  * hz_coefficients.tex  — AASTeX deluxetable fragment (\\input into the paper).

No model runs and no plotting: pure post-processing of hz_figure7.npz.  Re-run
after the HZ sweep cache changes.
"""

import os
import numpy as np

HERE    = os.path.dirname(os.path.abspath(__file__))
# Variant tag (HZ_FIG_SUFFIX): '' => the published files.  Set it together with
# HZ_ALBEDO/OHZ_ALBEDO so an albedo variant writes its own caches/figures and
# never overwrites the published ones.
SUF = os.environ.get('HZ_FIG_SUFFIX', '')
CACHE   = os.path.join(HERE, f"hz_figure7{SUF}.npz")
OUT_TXT = os.path.join(HERE, f"hz_coefficients{SUF}.txt")
OUT_TEX = os.path.join(HERE, f"hz_coefficients{SUF}.tex")

T_SUN = 5780.0  # K — Kopparapu reference temperature (T* = T_eff - T_SUN)

# Boundaries to fit: cache key, display label.
LIMITS = [
    ("seff_runaway", "Runaway greenhouse"),
    ("seff_inner",   "Moist greenhouse"),
    ("seff_outer",   "Maximum greenhouse"),
]


def fit_quartic(teff, seff):
    """Fit S_eff = S0 + a*T* + b*T*^2 + c*T*^3 + d*T*^4 (T* = teff - 5780).

    Returns (coeffs, rms) where coeffs = [S0, a, b, c, d] (ascending power) so
    that coeffs follows the Kopparapu Table-3 column order directly.
    """
    tstar = teff - T_SUN
    # np.polyfit returns highest-power first; flip to ascending [S0, a, b, c, d].
    p_desc = np.polyfit(tstar, seff, 4)
    coeffs = p_desc[::-1]
    resid = seff - np.polyval(p_desc, tstar)
    rms = float(np.sqrt(np.mean(resid**2)))
    return coeffs, rms


def main():
    d = np.load(CACHE, allow_pickle=True)
    teff = np.asarray(d["teff"], dtype=float)
    order = np.argsort(teff)
    teff = teff[order]
    tmin, tmax = float(teff.min()), float(teff.max())

    results = []
    for key, label in LIMITS:
        seff = np.asarray(d[key], dtype=float)[order]
        coeffs, rms = fit_quartic(teff, seff)
        results.append(dict(label=label, coeffs=coeffs, rms=rms))

    # ----------------------------------------------------------------- table
    lines = []
    lines.append("# ExoColumn habitable-zone boundary coefficients")
    lines.append("#")
    lines.append("#   S_eff(T_eff) = S_eff_sun + a*T* + b*T*^2 + c*T*^3 + d*T*^4")
    lines.append("#   T* = T_eff - 5780 K")
    lines.append(f"#   valid range: T_eff = {tmin:.0f} - {tmax:.0f} K")
    lines.append("#   distance:  d = sqrt( (L/L_sun) / S_eff )  AU")
    lines.append("#")
    lines.append("# Fit to ExoColumn (ExoRT n68equiv radiation core); same functional")
    lines.append("# form as Kopparapu et al. (2013,2014) Table 3, for direct substitution.")
    lines.append("#")
    lines.append(f"# {'boundary':<20s} {'S_eff_sun':>13s} {'a':>14s} {'b':>14s} "
                 f"{'c':>14s} {'d':>14s} {'rms':>10s}")
    for r in results:
        c = r["coeffs"]
        lines.append(f"  {r['label']:<20s} {c[0]:13.6f} {c[1]:14.6e} "
                     f"{c[2]:14.6e} {c[3]:14.6e} {c[4]:14.6e} {r['rms']:10.2e}")
    table = "\n".join(lines) + "\n"
    with open(OUT_TXT, "w") as f:
        f.write(table)
    print(table)
    print(f"wrote {OUT_TXT}")

    # ------------------------------------------------- LaTeX deluxetable frag
    def tex_sci(x):
        """Format a coefficient as m\\times10^{e} for an AASTeX cell."""
        if x == 0.0:
            return "0"
        e = int(np.floor(np.log10(abs(x))))
        m = x / 10.0**e
        return f"${m:.4f}\\times10^{{{e}}}$"

    tl = []
    tl.append("% Auto-generated by reference/habitablezone/hz_polyfit.py -- do not edit by hand.")
    tl.append("\\begin{deluxetable*}{lrrrrr}")
    # Bracketed placeholder caption (the author rewrites it); re-emitted on every
    # regeneration so it stays visible in the compiled PDF.
    tl.append("\\tablecaption{[ExoColumn habitable-zone boundary coefficients for "
              "the Kopparapu quartic $S_{\\rm eff}(T_{\\rm eff})$, fit to the model "
              "results over $T_{\\rm eff}=2000-7200$~K (RMS $\\sim10^{-3}\\,S_\\odot$); "
              "a drop-in replacement for Kopparapu et al. (2013, 2014) Table~3 with "
              "the ExoRT radiation core.]}")
    tl.append("\\tablehead{")
    tl.append("  \\colhead{HZ boundary} & \\colhead{$S_{\\rm eff,\\odot}$} &")
    tl.append("  \\colhead{$a$} & \\colhead{$b$} & \\colhead{$c$} & \\colhead{$d$}")
    tl.append("}")
    tl.append("\\startdata")
    for i, r in enumerate(results):
        c = r["coeffs"]
        end = " \\\\" if i < len(results) - 1 else ""
        tl.append(f"{r['label']} & {c[0]:.4f} & {tex_sci(c[1])} & {tex_sci(c[2])} & "
                  f"{tex_sci(c[3])} & {tex_sci(c[4])}{end}")
    tl.append("\\enddata")
    tl.append("\\tablecomments{$S_{\\rm eff}(T_{\\rm eff}) = S_{\\rm eff,\\odot} + a\\,T_\\star "
              "+ b\\,T_\\star^2 + c\\,T_\\star^3 + d\\,T_\\star^4$, with "
              f"$T_\\star = T_{{\\rm eff}} - 5780$~K, valid for $T_{{\\rm eff}} = {tmin:.0f}"
              f"-{tmax:.0f}$~K.}}")
    tl.append("\\label{tab:hz_coeff}")
    tl.append("\\end{deluxetable*}")
    with open(OUT_TEX, "w") as f:
        f.write("\n".join(tl) + "\n")
    print(f"wrote {OUT_TEX}")


if __name__ == "__main__":
    main()
